name:
  Django Testing and Deploy

on:
  push:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check updates
        uses: actions/checkout@v2

      - name: Python setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

#      - name: setup libs
#        run: |
#          pip install --upgrade pip |
#          pip install -r requirements.txt
#
#      - name: Linting of stocks_products
#        run: flake8 stocks_products
#
#      - name: Linting of logistic
#        run: flake8 logistic
